name: Deploy Minikube to AWS

on:
  push:
    branches:
      - Master
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform 
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      TF_VAR_aws_region: ap-south-1
      TF_VAR_project_name: minikube-demo
      TF_VAR_key_location: ./id_ed25519.pub
      TF_VAR_public_subnet_id: ${{ secrets.PUBLIC_SUBNET_ID }}
      TF_VAR_hosted_zone: ${{ secrets.HOSTED_ZONE }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform force-unlock plan

    - name: Terraform Apply
      run: terraform apply -auto-approve
